[package]
name = "rust_advent"
version = "0.1.0"
edition = "2024"

[dependencies]
hyperfine = "1.20.0"
rayon = "1.10"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "day03_benchmark"
harness = false